<?php

use Illuminate\Database\Seeder;
use App\Services\CategoryService;

class BusinessCategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $file =env('Business_URL');
        $categoryService = new CategoryService();
        $categoryService->categoriesImportBusiness($file);

//        $businesses = [
//            ['id'=>632 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Food and Entertainment/Traveling','type'=>'Business','is_active'=>1],
//
//            ['id'=>633 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Cafe','type'=>'Business','parent_id'=>632,'is_active'=>1],
//            ['id'=>634 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Restaurants','type'=>'Business','parent_id'=>632,'is_active'=>1],
//            ['id'=>635 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Bakeries','type'=>'Business','parent_id'=>632,'is_active'=>1],
//            ['id'=>636 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Fast Food Experts','type'=>'Business','parent_id'=>632,'is_active'=>1],
//            ['id'=>637 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Ice Cream Shops and Juice Bars','type'=>'Business','parent_id'=>632,'is_active'=>1],
//            ['id'=>638 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Art Design and Cinemas','type'=>'Business','parent_id'=>632,'is_active'=>1],
//            ['id'=>639 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Serviced Apartments','type'=>'Business','parent_id'=>632,'is_active'=>1],
//            ['id'=>640 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Musical Intilments Dealers and Shops','type'=>'Business','parent_id'=>632,'is_active'=>1],
//            ['id'=>641 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Travel Agency/Agents','type'=>'Business','parent_id'=>632,'is_active'=>1],
//            ['id'=>642 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Hostels','type'=>'Business','parent_id'=>632,'is_active'=>1],
//            ['id'=>643 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Hotel and Motels','type'=>'Business','parent_id'=>632,'is_active'=>1],
//
//            ['id'=>644 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Education','type'=>'Business','is_active'=>1],
//
//            ['id'=>645 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Schools','type'=>'Business','parent_id'=>644,'is_active'=>1],
//            ['id'=>646 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Colleges','type'=>'Business','parent_id'=>644,'is_active'=>1],
//            ['id'=>647 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Universities','type'=>'Business','parent_id'=>644,'is_active'=>1],
//            ['id'=>648 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Short Course and Training Centers','parent_id'=>644,'type'=>'Business','is_active'=>1],
//            ['id'=>649 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Madarsas','type'=>'Business','parent_id'=>644,'is_active'=>1],
//            ['id'=>650 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Academies','parent_id'=>644,'type'=>'Business','is_active'=>1],
//            ['id'=>651 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Technical Training Centers','parent_id'=>644,'type'=>'Business','is_active'=>1],
//            ['id'=>652 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Book and Study Material Suppliers','parent_id'=>644,'type'=>'Business','is_active'=>1],
//            ['id'=>653 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Freelance Tutors','parent_id'=>644,'type'=>'Business','is_active'=>1],
//            ['id'=>654 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Educational Equipment Suppliers','parent_id'=>644,'type'=>'Business','is_active'=>1],
//            ['id'=>655 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Uniform Dealers and Shops','parent_id'=>644,'type'=>'Business','is_active'=>1],
//
//            ['id'=>656 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Health and Fitness','type'=>'Business','is_active'=>1],
//
//            ['id'=>657 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Hospitals','parent_id'=>656,'type'=>'Business','is_active'=>1],
//            ['id'=>749 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Clinics','parent_id'=>656,'type'=>'Business','is_active'=>1],
//            ['id'=>658 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Chemist or Pharmist','parent_id'=>656,'type'=>'Business','is_active'=>1],
//            ['id'=>659 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Laboratories','parent_id'=>656,'type'=>'Business','is_active'=>1],
//            ['id'=>660 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Blood Banks','parent_id'=>656,'type'=>'Business','is_active'=>1],
//            ['id'=>661 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Health Insurance','parent_id'=>656,'type'=>'Business','is_active'=>1],
//            ['id'=>662 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Drug Dealers','parent_id'=>656,'type'=>'Business','is_active'=>1],
//            ['id'=>663 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Medical Equipment and Accessories Dealers','parent_id'=>656,'type'=>'Business','is_active'=>1],
//            ['id'=>664 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Fitness-Gym Centers','type'=>'Business','parent_id'=>656,'is_active'=>1],
//            ['id'=>665 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Fitness-Gym Equipment Dealers','parent_id'=>656,'type'=>'Business','is_active'=>1],
//            ['id'=>666 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Beautiy Saloon and Skin Treatment Centers','parent_id'=>656,'type'=>'Business','is_active'=>1],
//
//            ['id'=>667 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Fashion','type'=>'Business','is_active'=>1],
//
//            ['id'=>668 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Clothing','parent_id'=>667,'type'=>'Business','is_active'=>1],
//            ['id'=>669 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Boutiques and Ready to Wear','parent_id'=>667,'type'=>'Business','is_active'=>1],
//            ['id'=>670 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Shoes','parent_id'=>667,'type'=>'Business','is_active'=>1],
//            ['id'=>671 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Cosmetics and Body Care','parent_id'=>667,'type'=>'Business','is_active'=>1],
//            ['id'=>672 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Jewelry and Watches','parent_id'=>667,'type'=>'Business','is_active'=>1],
//            ['id'=>673 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Bags and Accessories','parent_id'=>667,'type'=>'Business','is_active'=>1],
//            ['id'=>674 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Beauty Salons','parent_id'=>667,'type'=>'Business','is_active'=>1],
//            ['id'=>675 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Fashion Designers','type'=>'Business','parent_id'=>667,'is_active'=>1],
//            ['id'=>676 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Sports Wear','type'=>'Business','parent_id'=>667,'is_active'=>1],
//            ['id'=>677 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Embroidery Services','type'=>'Business','parent_id'=>667,'is_active'=>1],
//            ['id'=>678 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Kids Accessories and Toys','type'=>'Business','parent_id'=>667,'is_active'=>1],
//
//            ['id'=>679 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Automobile and Transport','type'=>'Business','is_active'=>1],
//
//            ['id'=>680 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Automotive Leasing and Rental','parent_id'=>679,'type'=>'Business','is_active'=>1],
//            ['id'=>681 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Automotive Manufacturing','parent_id'=>679,'type'=>'Business','is_active'=>1],
//            ['id'=>682 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Automotive Parts','parent_id'=>679,'type'=>'Business','is_active'=>1],
//            ['id'=>683 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Automotive Accessories','parent_id'=>679,'type'=>'Business','is_active'=>1],
//            ['id'=>684 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Automotive Repair/Workshops','parent_id'=>679,'type'=>'Business','is_active'=>1],
//            ['id'=>685 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Automotive Sales and Purchase Dealers','parent_id'=>679,'type'=>'Business','is_active'=>1],
//            ['id'=>686 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Commercial Vehicle Dealers','parent_id'=>679,'type'=>'Business','is_active'=>1],
//            ['id'=>687 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Commercial Aerospace Dealers','type'=>'Business','parent_id'=>679,'is_active'=>1],
//            ['id'=>688 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Sporting Goods and Bicycles','type'=>'Business','parent_id'=>679,'is_active'=>1],
//            ['id'=>689 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Public Transport Providers','type'=>'Business','parent_id'=>679,'is_active'=>1],
//            ['id'=>690 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Security Solutions','type'=>'Business','parent_id'=>679,'is_active'=>1],
//
//
//            ['id'=>691 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Telecom and Computing','type'=>'Business','is_active'=>1],
//
//            ['id'=>692 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Voice/Call Center Services','parent_id'=>691,'type'=>'Business','is_active'=>1],
//            ['id'=>693 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Telecom Equipment And Accessories','parent_id'=>691,'type'=>'Business','is_active'=>1],
//            ['id'=>694 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'IT Security Companies','parent_id'=>691,'type'=>'Business','is_active'=>1],
//            ['id'=>695 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Mobile Phone Shops and Dealers','parent_id'=>691,'type'=>'Business','is_active'=>1],
//            ['id'=>696 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Computer/ Networking Shops and Dealers','parent_id'=>691,'type'=>'Business','is_active'=>1],
//            ['id'=>697 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Electronic Shops and Dealers','parent_id'=>691,'type'=>'Business','is_active'=>1],
//            ['id'=>698 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Hardware Shops and Dealers','parent_id'=>691,'type'=>'Business','is_active'=>1],
//            ['id'=>699 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Musical Instruments','type'=>'Business','parent_id'=>691,'is_active'=>1],
//            ['id'=>700 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Mobile Repairing','type'=>'Business','parent_id'=>691,'is_active'=>1],
//            ['id'=>701 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Software Companies','type'=>'Business','parent_id'=>691,'is_active'=>1],
//            ['id'=>702 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Cell Phones and Accessories','type'=>'Business','parent_id'=>691,'is_active'=>1],
//
//
//            ['id'=>703 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Services and Solutions','type'=>'Business','is_active'=>1],
//
//            ['id'=>704 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'IT Services and Solutions','parent_id'=>703,'type'=>'Business','is_active'=>1],
//            ['id'=>705 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Advertising and Printing Services','parent_id'=>703,'type'=>'Business','is_active'=>1],
//            ['id'=>706 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Courier and Cargo Services','parent_id'=>703,'type'=>'Business','is_active'=>1],
//            ['id'=>707 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Mirage Bureau and Services','parent_id'=>703,'type'=>'Business','is_active'=>1],
//            ['id'=>708 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Accounting and Taxation Services','parent_id'=>703,'type'=>'Business','is_active'=>1],
//            ['id'=>709 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Security Services','parent_id'=>703,'type'=>'Business','is_active'=>1],
//            ['id'=>710 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Legal Services','parent_id'=>703,'type'=>'Business','is_active'=>1],
//            ['id'=>711 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Photography Services','type'=>'Business','parent_id'=>703,'is_active'=>1],
//            ['id'=>712 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Consulting Services','type'=>'Business','parent_id'=>703,'is_active'=>1],
//            ['id'=>713 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Business Services','type'=>'Business','parent_id'=>703,'is_active'=>1],
//            ['id'=>714 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Business Process Outsourcing','type'=>'Business','parent_id'=>703,'is_active'=>1],
//
//            ['id'=>715 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Business and Companies','type'=>'Business','is_active'=>1],
//
//            ['id'=>716 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Import and Export','parent_id'=>715,'type'=>'Business','is_active'=>1],
//            ['id'=>717 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Recruitment/Employment Firms','parent_id'=>715,'type'=>'Business','is_active'=>1],
//            ['id'=>718 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Electronics and Home Appliances','parent_id'=>715,'type'=>'Business','is_active'=>1],
//            ['id'=>719 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Office Material and Stationary','parent_id'=>715,'type'=>'Business','is_active'=>1],
//            ['id'=>720 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Departmental Store','parent_id'=>715,'type'=>'Business','is_active'=>1],
//            ['id'=>721 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Travel Agents/Service Provider','parent_id'=>715,'type'=>'Business','is_active'=>1],
//            ['id'=>722 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Manufacturing Material','parent_id'=>715,'type'=>'Business','is_active'=>1],
//            ['id'=>723 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Consulting Material Services','type'=>'Business','parent_id'=>715,'is_active'=>1],
//            ['id'=>724 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Building Material Services','type'=>'Business','parent_id'=>715,'is_active'=>1],
//            ['id'=>725 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Construction Services','type'=>'Business','parent_id'=>715,'is_active'=>1],
//            ['id'=>726 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Property Dealers ','type'=>'Business','parent_id'=>715,'is_active'=>1],
//
//            ['id'=>727 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Home and Lifestyle','type'=>'Business','is_active'=>1],
//
//            ['id'=>728 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Furniture Shops and Dealers','parent_id'=>727,'type'=>'Business','is_active'=>1],
//            ['id'=>729 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Kitchen Ware','parent_id'=>727,'type'=>'Business','is_active'=>1],
//            ['id'=>730 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Home Decor','parent_id'=>727,'type'=>'Business','is_active'=>1],
//            ['id'=>731 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Grocery Shops','parent_id'=>727,'type'=>'Business','is_active'=>1],
//            ['id'=>732 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Law and Garden Services','parent_id'=>727,'type'=>'Business','is_active'=>1],
//            ['id'=>733 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Per Services','parent_id'=>727,'type'=>'Business','is_active'=>1],
//            ['id'=>734 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Tiler and Tiling Services','parent_id'=>727,'type'=>'Business','is_active'=>1],
//            ['id'=>735 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Timber Floor Supplies','type'=>'Business','parent_id'=>727,'is_active'=>1],
//            ['id'=>736 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Laundary and Cleaning','type'=>'Business','parent_id'=>727,'is_active'=>1],
//            ['id'=>737 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Bath and Bedding Accessories','type'=>'Business','parent_id'=>727,'is_active'=>1],
//
//
//
//            ['id'=>738 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Petrol Pumps','type'=>'Business','is_active'=>1],
//
//            ['id'=>739 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Bank and ATM','parent_id'=>738,'type'=>'Business','is_active'=>1],
//            ['id'=>740 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Mosque','parent_id'=>738,'type'=>'Business','is_active'=>1],
//            ['id'=>741 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Shopping Malls','parent_id'=>738,'type'=>'Business','is_active'=>1],
//            ['id'=>742 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Wedding Halls','parent_id'=>738,'type'=>'Business','is_active'=>1],
//            ['id'=>743 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Airport','parent_id'=>738,'type'=>'Business','is_active'=>1],
//            ['id'=>744 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Government','parent_id'=>738,'type'=>'Business','is_active'=>1],
//            ['id'=>745 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'News/Events','parent_id'=>738,'type'=>'Business','is_active'=>1],
//            ['id'=>746 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Public Parts and Visit Places','type'=>'Business','parent_id'=>727,'is_active'=>1],
//            ['id'=>747 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>'Farming','type'=>'Business','parent_id'=>738,'is_active'=>1],
//            ['id'=>748 , 'profile_image'=>'project-assets/images/categories/weddinghalls.jpg',
//                'name'=>"Charity-NGO's-Volunteers",'type'=>'Business','parent_id'=>738,'is_active'=>1],
//        ];
//
//
//        foreach ($businesses as $business) {
//            \App\Category::create($business);;
//        }
    }
}
